import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'

const isContentEditor = ({ req: { user } }: any) =>
  ['super-admin', 'admin', 'content-editor'].includes(user?.role)

export const BlogPosts: CollectionConfig = {
  slug: 'blog-posts',
  admin: {
    useAsTitle: 'title',
    group: 'Content',
    defaultColumns: ['title', 'category', 'publishedDate', 'status'],
    description: 'Blog articles and insights — Phase 2: Pritom will auto-generate content here',
  },
  access: {
    read: ({ req: { user } }) => {
      // Published posts visible to all; drafts only to editors+
      if (!user) return { status: { equals: 'published' } }
      if (['super-admin', 'admin', 'content-editor'].includes(user.role)) return true
      return { status: { equals: 'published' } }
    },
    create: isContentEditor,
    update: isContentEditor,
    delete: ({ req: { user } }) => ['super-admin', 'admin'].includes(user?.role || ''),
  },
  versions: {
    drafts: true,
  },
  fields: [
    { name: 'title', type: 'text', required: true },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'category',
      type: 'select',
      options: [
        { label: 'Game Art Insights', value: 'game-art' },
        { label: 'Industry News', value: 'industry' },
        { label: 'Case Studies', value: 'case-studies' },
        { label: 'XR & Simulation', value: 'xr' },
        { label: 'Studio Updates', value: 'studio' },
        { label: 'AI & Technology', value: 'ai' },
      ],
    },
    { name: 'excerpt', type: 'textarea', admin: { description: 'Short summary for listing pages and SEO' } },
    { name: 'heroImage', type: 'upload', relationTo: 'media' },
    { name: 'content', type: 'richText', editor: lexicalEditor({}) },
    { name: 'author', type: 'relationship', relationTo: 'users' },
    { name: 'publishedDate', type: 'date' },
    {
      name: 'tags',
      type: 'array',
      fields: [{ name: 'tag', type: 'text' }],
    },
    { name: 'readingTime', type: 'number', admin: { description: 'Estimated reading time in minutes' } },
    {
      name: 'seo',
      type: 'group',
      label: 'SEO',
      fields: [
        { name: 'metaTitle', type: 'text' },
        { name: 'metaDescription', type: 'textarea' },
        { name: 'ogImage', type: 'upload', relationTo: 'media' },
        { name: 'keywords', type: 'text', admin: { description: 'Comma-separated keywords' } },
      ],
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'draft',
      options: [
        { label: 'Published', value: 'published' },
        { label: 'Draft', value: 'draft' },
        { label: 'Archived', value: 'archived' },
      ],
    },
    {
      name: 'pritomGenerated',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Phase 2: marks content auto-generated by Pritom AI',
      },
    },
  ],
}
