import { CollectionConfig } from 'payload/types'

const isEditor = ({ req: { user } }: any) =>
  !!user && ['super-admin', 'admin', 'content-editor'].includes(user.role)

// ─── Team Members ───────────────────────────────────────────────────────────
export const TeamMembers: CollectionConfig = {
  slug: 'team-members',
  admin: {
    useAsTitle: 'name',
    group: 'Content',
    defaultColumns: ['name', 'role', 'hub', 'order'],
  },
  access: {
    read:   () => true,
    create: isEditor,
    update: isEditor,
    delete: ({ req: { user } }) => !!user && ['super-admin', 'admin'].includes(user.role),
  },
  fields: [
    { name: 'name',  type: 'text', required: true },
    { name: 'role',  type: 'text', required: true, admin: { description: 'e.g. Co-Founder & CEO' } },
    {
      name: 'hub',
      type: 'select',
      options: [
        { label: 'Vienna (HQ)',         value: 'vienna' },
        { label: 'Dubai (MENA)',        value: 'dubai' },
        { label: 'Dhaka (Production)',  value: 'dhaka' },
      ],
    },
    { name: 'bio',    type: 'textarea' },
    { name: 'photo',  type: 'upload', relationTo: 'media' },
    { name: 'linkedin', type: 'text', admin: { description: 'Full LinkedIn URL' } },
    { name: 'order',  type: 'number', defaultValue: 0 },
  ],
}

// ─── Clients (Social Proof Logo Strip) ──────────────────────────────────────
export const Clients: CollectionConfig = {
  slug: 'clients',
  admin: {
    useAsTitle: 'name',
    group: 'Content',
    defaultColumns: ['name', 'featured', 'order'],
    description: 'Client logos shown in the social proof strip on the homepage.',
  },
  access: {
    read:   () => true,
    create: isEditor,
    update: isEditor,
    delete: ({ req: { user } }) => !!user && ['super-admin', 'admin'].includes(user.role),
  },
  fields: [
    { name: 'name',     type: 'text', required: true },
    {
      name: 'logo',
      type: 'upload',
      relationTo: 'media',
      required: true,
      admin: { description: 'White/light version of logo for dark background. SVG or PNG with transparency preferred.' },
    },
    { name: 'website',  type: 'text', admin: { description: 'Optional: client website URL' } },
    {
      name: 'featured',
      type: 'checkbox',
      defaultValue: true,
      admin: { description: 'Show in homepage logo strip' },
    },
    { name: 'order', type: 'number', defaultValue: 0 },
  ],
}

// ─── Blog Posts ──────────────────────────────────────────────────────────────
export const BlogPosts: CollectionConfig = {
  slug: 'blog-posts',
  admin: {
    useAsTitle: 'title',
    group: 'Content',
    defaultColumns: ['title', 'author', 'status', 'publishedAt', 'updatedAt'],
    preview: (doc) => `${process.env.NEXT_PUBLIC_SITE_URL}/blog/${doc.slug}`,
    description: 'Blog & Insights. Phase 2: Pritom will auto-generate and publish articles here.',
  },
  access: {
    read: ({ req: { user } }) => {
      if (user) return true
      return { status: { equals: 'published' } }
    },
    create: isEditor,
    update: isEditor,
    delete: ({ req: { user } }) => !!user && ['super-admin', 'admin'].includes(user.role),
  },
  versions: {
    drafts: true,
  },
  fields: [
    { name: 'title', type: 'text', required: true },
    { name: 'slug',  type: 'text', required: true, unique: true },
    {
      name: 'author',
      type: 'relationship',
      relationTo: 'users',
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'media',
    },
    {
      name: 'excerpt',
      type: 'textarea',
      admin: { description: 'Short summary shown on blog listing page and in SEO description.' },
    },
    {
      name: 'content',
      type: 'richText',
    },
    {
      name: 'tags',
      type: 'array',
      fields: [{ name: 'tag', type: 'text' }],
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'draft',
      options: [
        { label: 'Published', value: 'published' },
        { label: 'Draft',     value: 'draft' },
      ],
    },
    {
      name: 'publishedAt',
      type: 'date',
      admin: { description: 'Leave blank to use current date on publish.' },
    },
    {
      name: 'generatedByPritom',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Phase 2: Mark if this article was generated by Pritom AI.',
        position: 'sidebar',
      },
    },
    {
      name: 'seo',
      label: 'SEO',
      type: 'group',
      fields: [
        { name: 'title', type: 'text' },
        { name: 'description', type: 'textarea' },
        { name: 'ogImage', label: 'OG Image', type: 'upload', relationTo: 'media' },
      ],
    },
  ],
}
