import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'
import { sql } from '@payloadcms/db-postgres'

// For version tables, Payload passes array child fields through idToUUID(),
// which renames the "id" field to "_uuid". setColumnID() then finds no "id"
// field and generates a fresh serial primary key. Result: every version child
// table has "id serial PRIMARY KEY" (not varchar) PLUS a "_uuid varchar" column.
//
// Our earlier migrations had "id varchar PRIMARY KEY" and no "_uuid" column —
// the wrong schema. This migration drops and recreates all version child tables
// with the correct schema.

export async function up({ db }: MigrateUpArgs): Promise<void> {

  // ── Drop all version child tables (CASCADE removes FK constraints) ────────
  await db.execute(sql`DROP TABLE IF EXISTS "_home_page_v_version_stats" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_credentials" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_hubs" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_why_xqube" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_services_page_v_version_pipelines_steps" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_services_page_v_version_pipelines" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_navigation_v_version_main_nav" CASCADE;`)

  // ── Recreate with correct schema ──────────────────────────────────────────
  // id   → serial PRIMARY KEY (auto-generated by setColumnID since no "id" in fields)
  // _uuid → varchar (the original UUID value, renamed from "id" by idToUUID())
  // _parent_id → integer (references the parent _*_v table id, which is serial)

  await db.execute(sql`
    CREATE TABLE "_home_page_v_version_stats" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "value"      varchar,
      "label"      varchar
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_about_page_v_version_credentials" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "value"      varchar,
      "label"      varchar,
      "detail"     varchar
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_about_page_v_version_hubs" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "flag"       varchar,
      "city"       varchar,
      "country"    varchar,
      "role"       varchar,
      "detail"     varchar,
      "image_id"   integer
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_about_page_v_version_why_xqube" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "title"      varchar,
      "body"       varchar
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_services_page_v_version_pipelines" (
      "_order"      integer NOT NULL,
      "_parent_id"  integer NOT NULL,
      "id"          serial PRIMARY KEY NOT NULL,
      "_uuid"       varchar,
      "title"       varchar,
      "subtitle"    varchar,
      "description" varchar,
      "tools_used"  varchar,
      "image_id"    integer
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_services_page_v_version_pipelines_steps" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "step"       varchar
    );
  `)

  await db.execute(sql`
    CREATE TABLE "_navigation_v_version_main_nav" (
      "_order"     integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id"         serial PRIMARY KEY NOT NULL,
      "_uuid"      varchar,
      "label"      varchar,
      "url"        varchar
    );
  `)

  // ── Indexes ───────────────────────────────────────────────────────────────
  await db.execute(sql`CREATE INDEX "_home_page_v_version_stats_order_idx"         ON "_home_page_v_version_stats"                USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_home_page_v_version_stats_parent_idx"        ON "_home_page_v_version_stats"                USING btree ("_parent_id");`)

  await db.execute(sql`CREATE INDEX "_about_page_v_version_credentials_order_idx"  ON "_about_page_v_version_credentials"         USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_about_page_v_version_credentials_parent_idx" ON "_about_page_v_version_credentials"         USING btree ("_parent_id");`)
  await db.execute(sql`CREATE INDEX "_about_page_v_version_hubs_order_idx"         ON "_about_page_v_version_hubs"                USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_about_page_v_version_hubs_parent_idx"        ON "_about_page_v_version_hubs"                USING btree ("_parent_id");`)
  await db.execute(sql`CREATE INDEX "_about_page_v_version_why_xqube_order_idx"    ON "_about_page_v_version_why_xqube"           USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_about_page_v_version_why_xqube_parent_idx"   ON "_about_page_v_version_why_xqube"           USING btree ("_parent_id");`)

  await db.execute(sql`CREATE INDEX "_services_page_v_version_pipelines_order_idx"       ON "_services_page_v_version_pipelines"       USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_services_page_v_version_pipelines_parent_idx"      ON "_services_page_v_version_pipelines"       USING btree ("_parent_id");`)
  await db.execute(sql`CREATE INDEX "_services_page_v_version_pipelines_steps_order_idx" ON "_services_page_v_version_pipelines_steps" USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_services_page_v_version_pipelines_steps_parent_idx" ON "_services_page_v_version_pipelines_steps" USING btree ("_parent_id");`)

  await db.execute(sql`CREATE INDEX "_navigation_v_version_main_nav_order_idx"     ON "_navigation_v_version_main_nav"            USING btree ("_order");`)
  await db.execute(sql`CREATE INDEX "_navigation_v_version_main_nav_parent_idx"    ON "_navigation_v_version_main_nav"            USING btree ("_parent_id");`)

  // ── Foreign keys ──────────────────────────────────────────────────────────
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_home_page_v_version_stats"
        ADD CONSTRAINT "_home_page_v_version_stats_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_home_page_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_about_page_v_version_credentials"
        ADD CONSTRAINT "_about_page_v_version_credentials_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_about_page_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_about_page_v_version_hubs"
        ADD CONSTRAINT "_about_page_v_version_hubs_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_about_page_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_about_page_v_version_hubs"
        ADD CONSTRAINT "_about_page_v_version_hubs_image_id_fk"
        FOREIGN KEY ("image_id") REFERENCES "media"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_about_page_v_version_why_xqube"
        ADD CONSTRAINT "_about_page_v_version_why_xqube_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_about_page_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_services_page_v_version_pipelines"
        ADD CONSTRAINT "_services_page_v_version_pipelines_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_services_page_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_services_page_v_version_pipelines"
        ADD CONSTRAINT "_services_page_v_version_pipelines_image_id_fk"
        FOREIGN KEY ("image_id") REFERENCES "media"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_services_page_v_version_pipelines_steps"
        ADD CONSTRAINT "_services_page_v_version_pipelines_steps_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_services_page_v_version_pipelines"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "_navigation_v_version_main_nav"
        ADD CONSTRAINT "_navigation_v_version_main_nav_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "_navigation_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`DROP TABLE IF EXISTS "_home_page_v_version_stats" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_credentials" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_hubs" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_about_page_v_version_why_xqube" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_services_page_v_version_pipelines_steps" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_services_page_v_version_pipelines" CASCADE;`)
  await db.execute(sql`DROP TABLE IF EXISTS "_navigation_v_version_main_nav" CASCADE;`)
}
